### ISSUE TITLE
[FEATURE] Support other (SQL / PostgreSQL) databases

### ISSUE THREAD

**Issue by chrisstaudt** [nmshd/feedback#13]
**Environment**
 Connector

**Is your feature request related to a problem? Please describe.**
We use PostgreSQL as our main database and I would like to avoid to run a separate mongo db cluster only for the connector.

**Describe the solution you'd like**
It would be great if you could support different databases. Most SQL databases support efficient document storage by now as well so it is usually quite straightforward to support them without putting too much effort in the database schema. 

**Describe alternatives you've considered**
I guess the only alternative is to just use MongoDB?

**Comment by stnmtz** [comment]
Hi @CSNWEB,

thank you for your request. We would love to see PostgreSQL support (or in that sense any other database). However, we lack the resources to implement this in the near future.

So yes, you have to unfortunately stick with MongoDB, unless you could implement some PostgreSQL mapper on your own. Our database mappers are implemented in https://github.com/js-soft/ts-documentdb-access 

Best Regards

**Comment by chrisstaudt** [comment]
Hello @stnmtz,

thanks for you quick answer. I had very rough look over ts-documentdb-access and I think I could implement a postgresql version of it. But it also seems like mongodb is "hardcoded" in the connector, so you / we would either have to ship my connector with the app and provide a configuration option for it or at least make it a parameter in some place so I can use it as a library (if that is even a somewhat supported use case?). I wouldn't want to fork the connector and keep up with the changes from your side.

**Comment by jkoenig134** [comment]
@CSNWEB the big problem will be MongoDB query compatibility. If you can archieve that we are good to go.

We will build a switch in the connector that you can use your DB wrapper when it is finished.

**Comment by chrisstaudt** [comment]
Ah I see now that you actually allow arbitrary mongodb queries. That will indeed be a problem. There is this package: https://www.npmjs.com/package/mongo-query-to-postgres-jsonb which claims to convert them to postgres where conditions, but I am not sure how well that would really work. The wrapper pgmongo seems to support around 20% of all mongodb tests. Is this actually required or are most calls simpler lookups and it would be possible to use a simpler more restricted query API plus some extra methods for the really difficult cases? Otherwise supporting other databases seems to be very difficult.

**Comment by jkoenig134** [comment]
Yes, the http query is translated to a mongodb query and then directly given to the find method of the mongodb.

So we will need an query compatibility with mongodb as documented in the querystring  package.

**Comment by jkoenig134** [comment]
Hi  @CSNWEB!
I provided an [example repo](https://github.com/jkoenig134/nmshd_ferret_connector) for running the Enmeshed Connector on Postgres using [FerretDB](https://www.ferretdb.io/) which proxies MongoDB calls to a postgres database.

It is in an early stage and we do not recommend using it in production but maybe it serves your needs.
