### ISSUE TITLE
CLIENT_ID and CLIENT_SECRET for Docker needed

### ISSUE THREAD

**Issue by SohrabHejaziTu** [nmshd/feedback#19]
after running the Docker of enmeshed- connector, ghcr.io/nmshd/connector can not communicate with Mongo-container and I get the following error:
### The combination of platform clientId and clientSecret is invalid

Actually, we need CLIENT_ID and CLIENT_SECRET which are not available in the document.
Could you please help us?

**Comment by jkoenig134** [comment]
Hi! You can get more information on how to configure the connector [in our documentation](https://enmeshed.eu/integrate/connector-configuration#transportlibrary).

**Comment by SohrabHejaziTu** [comment]
I have never found any info about CLIENT_ID and CLIENT_SECRET in this document. I read several times all pages about enmeshed and connector on your website and check all possibilities and run 100 times the dockers. Why did you close the ticket without solving the problem?
Everything goes well but The problem is between the connector and the Mango container and we always get the following error message: The combination of platform clientId and clientSecret is invalid
I checked all possibilities.
 PLEASE LET ME KNOW what are CLIENT_ID and CLIENT_SECRET. 
where/how can we get it?

**Comment by tnotheis** [comment]
The link @jkoenig134 sent you points to the exact paragraph that tells you how to get CLIENT_ID and CLIENT_SECRET:

> The client id is required to communicate with the Enmeshed platform. It can be acquired from the [Enmeshed Support](https://enmeshed.eu/integrate/basics#support).

**Comment by SohrabHejaziTu** [comment]
I am aware, I sent an email to support@enmeshed.eu and ask them but no feedback no response.
 @jkoenig134 did not guide me properly and only sent a link that I have read and followed ten times and it was of no value to solve my problem.
my request is clear  "We need CLIENT_ID and CLIENT_SECRET"

**Comment by jkoenig134** [comment]
You should have received a mail.
This repository is not the correct place to discuss this topic.
