### ISSUE TITLE
[BUG] Can not use Connector behind Proxy due to upstream bug

### ISSUE THREAD

**Issue by HoffmannP** [nmshd/feedback#21]
**Describe the bug**
The connector can not be used behind a proxy due to problems with axios library (see https://github.com/axios/axios/issues/925)

**To Reproduce**
1. Start connector behind proxy with https_proxy env variable set
2. Axios does not create a CONNECTION as required for proxying TLS but starts a simple request to the proxy

**Expected behavior**
connector working

**Comment by HoffmannP** [comment]
A new version of the issue has been opened: https://github.com/axios/axios/issues/6330
Also see the following for a short reproduction of the issue: https://codesandbox.io/p/devbox/admiring-panini-rp2pyr
It would be possible to use axios and overcome the problem: https://codesandbox.io/p/devbox/lively-meadow-j3834n

**Comment by jkoenig134** [comment]
Hi Peter! Thanks for this detailed bug report.

I created a PR that should fix your issue. Would you be willing to verify that this works for you? For testing purposes I created an image for you: `jkoenig134/connector-with-http-proxy:latest`.

**Comment by HoffmannP** [comment]
I assume `ghcr.io/jkoenig134/connector-with-http-proxy:latest`? Docker responds with `manifest unknown`

**Comment by jkoenig134** [comment]
no, it's hosted on docker hub. So without `ghcr.io/`!

**Comment by HoffmannP** [comment]
The image works and connects without any problems.

**Comment by jkoenig134** [comment]
@HoffmannP [Connector version 3.9.4](https://github.com/nmshd/connector/pkgs/container/connector/200772877?tag=3.9.4) is now available with the fix.
