### ISSUE TITLE
[FEATURE] In the connector, support MongoDB database names that don't start with "acc-"

### ISSUE THREAD

**Issue by blalasaadri** [nmshd/feedback#22]
**Environment**
Connector

**Is your feature request related to a problem? Please describe.**
We deploy our instance of the connector in a cloud environment, where we don't have control over the name assigned to our MongoDB databases. However due to the following line in the `initAccount` method of ConnectorRuntime.ts, this doesn't work:
```ts
const db = await this.transport.createDatabase(`acc-${this.runtimeConfig.database.dbName}`);
```
As can be seen here, the connector requires the database name to always start with `acc-`.

**Describe the solution you'd like**
Rather than always requiring this prefix, it should be possible to fully configure the database name.
For backwards compatibility reasons, I would suggest the following in the `ConnectorRuntime.ts`:
```ts
const db = await this.transport.createDatabase(`${this.runtimeConfig.database.dbNamePrefix ?? 'acc-'}${this.runtimeConfig.database.dbName}`);
```
This means that an optional `dbNamePrefix` can be passed in the configuration. If no such parameter is given, the behaviour remains unchanged.
In our case, the relevant part of the config looks like this:
```json
{
 "database": {
    "dbNamePrefix": ""
  }
}
```

**Describe alternatives you've considered**
Currently we're running patch files on four files to enable the desired behaviour. I have attached these patch files as part of this ticket; in our own Dockerfile (which is a modified copy of the [Connector Dockerfile](https://github.com/nmshd/connector/blob/main/Dockerfile) we run the patches as follows:
```Dockerfile
# basic setup, of the builder, retrieve the code (ommited for brevity)

COPY build/ConnectorRuntime.ts.patch ConnectorRuntime.ts.patch
RUN patch src/ConnectorRuntime.ts < ConnectorRuntime.ts.patch
COPY build/ConnectorRuntimeConfig.ts.patch ConnectorRuntimeConfig.ts.patch
RUN patch src/ConnectorRuntimeConfig.ts < ConnectorRuntimeConfig.ts.patch
COPY build/connectorConfig.json.patch connectorConfig.json.patch
RUN patch src/jsonSchemas/connectorConfig.json < connectorConfig.json.patch
COPY build/connectorConfig.ts.patch connectorConfig.ts.patch
RUN patch src/jsonSchemas/connectorConfig.ts < connectorConfig.ts.patch

RUN npm ci

RUN npm run build

RUN .ci/writeBuildInformation.sh
```
If this feature were to be implemented, we could use the provided Docker image instead.

**Our patch files**
[connectorConfig.json.patch](https://github.com/nmshd/feedback/files/15235510/connectorConfig.json.patch) (for the `src/jsonSchemas/connectorConfig.json`)
[connectorConfig.ts.patch](https://github.com/nmshd/feedback/files/15235511/connectorConfig.ts.patch) (for the `src/jsonSchemas/connectorConfig.ts`)
[ConnectorRuntime.ts.patch](https://github.com/nmshd/feedback/files/15235512/ConnectorRuntime.ts.patch) (for the `src/ConnectorRuntime.ts`)
[ConnectorRuntimeConfig.ts.patch](https://github.com/nmshd/feedback/files/15235513/ConnectorRuntimeConfig.ts.patch) (for the `src/ConnectorRuntimeConfig.ts`)

**Comment by jkoenig134** [comment]
Hi @blalasaadri thanks for the detailed feature request. 

I have created a PR that should fix your problem.
When this is merged you can simply add the following to your config:

```json
{
  "database": {
    "dbNamePrefix": ""
  }
}
```

**Comment by jkoenig134** [comment]
@blalasaadri [connector version 3.10.1](https://github.com/nmshd/connector/pkgs/container/connector/213111000?tag=3.10.1) is now available, feel free to try it out and report back!

**Comment by blalasaadri** [comment]
Thank you @jkoenig134, that was very fast and it works perfectly. 🙂

**Comment by jkoenig134** [comment]
Glad to hear that your issue is fixed!
