### ISSUE TITLE
[BUG] Can not pull docker image

### ISSUE THREAD

**Issue by HoffmannP** [nmshd/feedback#23]
**Describe the bug**
I can not pull the latest image from the repository as I get an access denied error

**To Reproduce**
Everytime I try to pull the repository I can't because denied/forbitten
```sh
> podman pull ghcr.io/nmshd/connector:3.11.1
Trying to pull ghcr.io/nmshd/connector:3.11.1...
Error: initializing source docker://ghcr.io/nmshd/connector:3.11.1: Requesting bear token: invalid status code from registry 403 (Forbidden)

> buildah pull ghcr.io/nmshd/connector:3.10.1
Trying to pull ghcr.io/nmshd/connector:3.11.1...
initializing source docker://ghcr.io/nmshd/connector:3.11.1: Requesting bear token: invalid status code from registry 403 (Forbidden)
ERRO[0000] exit status 125

> docker pull ghcr.io/nmshd/connector:3.11.1
Error response from daemon: Head "https://ghcr.io/v2/nmshd/connector/manifests/3.11.1": denied: denied
```

**Expected behavior**
Getting da image

**Screenshots**
![image](https://github.com/nmshd/feedback/assets/432592/ddd34a2e-996a-4dd2-b71c-0179071cb280)

**Environment**
 - Product: Connector
 - Version: 3.11.1 or any other version
 - Device: PC
 - OS: Linux

Might be linked to this error: https://github.com/containers/podman/issues/18428

**Comment by sebbi08** [comment]
Hi, I just tried it on a new VM, and it works fine for me

![image](https://github.com/nmshd/feedback/assets/9070136/bbe287f9-745c-4426-925b-13d9f6a51b2c)


Is pinging `ghcr.io` working for you ?

**Comment by sebbi08** [comment]
I don't meant `ping`  but `curl/wget`

**Comment by HoffmannP** [comment]
So it looks like the error is indeed a GitHub/ghcr-error. I am logged in with docker (and podman/buildah) use the login token. But as I'm not specifically authorized for this repository ghcr declines my pull request. I removed the login token and now it works. Would be nice if you'd escalate the error. I'm closing this for now.

**Comment by HoffmannP** [comment]
Seems to be this issue: https://stackoverflow.com/a/74656301/2210887
