### ISSUE TITLE
[BUG] Can not use Connector behind Proxy (again)

### ISSUE THREAD

**Issue by HoffmannP** [nmshd/feedback#24]
**Describe the bug**
Please see https://github.com/nmshd/feedback/issues/21

**To Reproduce**
1. add proxy server configuration to env variables of enmashed server (e.g. squid)
```yaml
            - name: https_proxy
              value: http://your-proxy-address.tld:3128
```
2. try health check
3. fails

**Expected behavior**
Works

**Screenshots**
![image](https://github.com/nmshd/feedback/assets/432592/9e793251-8f53-47e3-a302-c69ba4d02862)

**Environment**
 - Product: Connector
 - Version: 3.11.1

**Comment by sebbi08** [comment]
Hi it seems that this is actually the other way around the #21 issue was the communication from connector -> backbone.

Here it looks to me that there is a revers proxy in front of the connector. Did you make sure that the connection from reverse proxy to connect is only http and not https as the connector itself is not serving over https

**Comment by sebbi08** [comment]
Hi, sry I assumed that https://nmshd-bkb.demo.meinbildungsraum.de/health is a connector URL and not the backbone, so ignore my previous answer.

Nevertheless, I think the problem is the connection from proxy to backbone.

Can you try and open then Health check endpoint in a browser ?
And is there a more detailed error description?
Looks like the proxy could not establish a secure connection to the backbone.

**Comment by HoffmannP** [comment]
Yes, it looks that way but I can without any problems run
```bash
https_proxy=http://internet4nzm.rz.uni-jena.de:3128 curl https://nmshd-bkb.demo.meinbildungsraum.de/health
```

Squid Log:
```
2024-05-25T00:19:30.855655+02:00 proxy02@proxy02.rz squid[2135]: 1716589170.854    359 10.138.32.35 TCP_TUNNEL/200 4517 CONNECT nmshd-bkb.demo.meinbildungsraum.de:443 - HIER_DIRECT/34.102.154.160 -
```

**Comment by HoffmannP** [comment]
Using the enmashed connector container 3.11.1 I get the following in the squid log
```
2024-05-25T01:01:46.540143+02:00 proxy01@proxy01.rz squid[2358]: 1716591706.539     29 10.136.56.12 TCP_MISS/503 4528 GET https://nmshd-bkb.demo.meinbildungsraum.de/health - HIER_NONE/- text/html
2024-05-25T01:01:46.581063+02:00 proxy02@proxy02.rz squid[2135]: 1716591706.580     24 10.136.56.12 TCP_MISS/503 4674 POST https://nmshd-bkb.demo.meinbildungsraum.de/connect/token - HIER_NONE/- text/html
```

**Comment by HoffmannP** [comment]
Even when I copy a curl binary into the running container I can open the health check. 
But when I open node in `/usr/app` inside the container and run
```js
const url = 'https://nmshd-bkb.demo.meinbildungsraum.de/health'
const axios = require('axios')
axios.get(url).then(response => { console.log(response.data) }).catch(error => { console.log('response' in error ? error.response.data : error.cause) })
```
I get the same error as in my screenshot

**Comment by sebbi08** [comment]
Ok, but the requests reach the proxy.
Can the proxy log the complete incoming request?
It would be good to see all the headers that get to the Squid proxy. And if they are different between the curl and the Axios command

**Comment by HoffmannP** [comment]
Unfortunately I don't have any more information I can provide.

**Comment by jkoenig134** [comment]
@HoffmannP https://github.com/nmshd/feedback/issues/21 has fixed your problem, right?
If you go back to [3.9.4](https://github.com/nmshd/connector/pkgs/container/connector/200772877?tag=3.9.4) does it work again?

**Comment by HoffmannP** [comment]
I just tried that and it does not work (same error as 3.11.1)

**Comment by jkoenig134** [comment]
As it worked before - can it be that something at your proxy changed?

**Comment by HoffmannP** [comment]
I was able to build a setup for the problem: https://github.com/HoffmannP/setup_nmshd_proxytest
If you run `deploy.sh` log files for direct and indirect request via the connector will be created.
You need to fill out some variables in `Secret.yaml` before deploying.

It might be possible, my setup using 3.9.4 was a false positive, I hand tweaked some stuff I did not commit in my deployment so unfortunately I can not recover the previous deployment.

Currently it looks like the connector is not trying to do a proper CONNECT required for TLS-over-Proxy but some TLS-encrypted request designed for my endpoint but sent to the proxy (as a usual non-TLS proxy request would be).

**Comment by jkoenig134** [comment]
@HoffmannP I deployed a squid proxy locally (without any settings applied) and for me this worked.

I maybe have found a bug that could cause issues, but I can not test this as I cannot reproduce your bug. I updated the `jkoenig134/connector-with-http-proxy:latest` image with my bugfix, would be great if you can test it out.

**Comment by jkoenig134** [comment]
I created a minimal example https://github.com/jkoenig134/nmshd-connector-squid you can also check this out.

**Comment by jkoenig134** [comment]
@HoffmannP I think I found the issue. I switched to the backbone you are using (`https://nmshd-bkb.demo.meinbildungsraum.de`) and for me this also fails. For backbones this works fine. I assume you have to talk about the people managing this backbone, maybe they disable proxy in any way.

**Comment by HoffmannP** [comment]
Thanks for the follow up, I just forwarded the bug report to our partners and hope they figure out the problem. I'd suggest we keep this open, until the issue is fixed.

**Comment by jkoenig134** [comment]
Fine for me.

**Comment by jkoenig134** [comment]
@HoffmannP I think I found the solution. I'll create a release asap for you to try it out.

**Comment by jkoenig134** [comment]
@HoffmannP version `3.11.3` of the connector [is now available](https://github.com/nmshd/connector/pkgs/container/connector/224578856?tag=3.11.3). Please test it out.

**Comment by jkoenig134** [comment]
Please check again with `3.11.4`, the health check is now also using the https proxy.

**Comment by HoffmannP** [comment]
3.11.4 looks good, thank you!
