### ISSUE TITLE
[BUG] Connector API: RequestContent misses @type

### ISSUE THREAD

**Issue by nenock** [nmshd/feedback#29]
When requesting a `RelationshipTemplate` via GET api/v2/RelationshipTemplates, the returned `RelationshipTemplateContents` of the templates aren't API-conform:
According to the API schema the `RelationshipTemplate`'s content `RelationshipTemplateContent` contains `onNewRelationship` which is a `RequestContent` and thus requires the property `@type`, but the API response misses that.

**To Reproduce**
1. Load the API schema with (or any other validation tool):
 ```ruby
schema = JSONSchemer.openapi(YAML.safe_load_file(<path-to-file>), permitted_classes: [Time, Date]))
```
2. Query relationship templates via `GET api/v2/RelationshipTemplates`
3. Pass the one of the results to:
```ruby
schema.valid?(<first-result>)
```
4. To see the error details, pass the result of one of the relationships to:
```ruby
puts schema.validate(<first-result>).first.fetch('error')
```
5. See error
```
object at `/template/content/onNewRelationship` is missing required properties: @type
```

**Expected behavior**
Please add the `@type` to the Connector's `RequestContent` responses.

**Environment**
 - Product: Connector
 - Version:  6.5.2 (API: 3.0.1)

**Comment by jkoenig134** [comment]
Hi @nenock!

Thanks for your bug report. I'll investigate and get back if I have more news!

**Comment by jkoenig134** [comment]
@nenock I just published [version 6.5.3 of the connector](https://github.com/nmshd/connector/releases/tag/6.5.3), the image should be available soon. Please re-check, but make sure to download the new openapi spec as the issue was the specification and not the code!

**Comment by jkoenig134** [comment]
[Image](https://github.com/nmshd/connector/pkgs/container/connector/302072152?tag=6.5.3) and [helm chart](https://github.com/nmshd/connector/pkgs/container/connector-helm-chart/302072584?tag=6.5.3) are available now!

**Comment by nenock** [comment]
@jkoenig134 I just found another one:

`object at /creationContent/response is missing required properties: @type`

**Comment by nenock** [comment]
Also, when requesting a `Relationship`, the result contains a `peerIdentity`, but that is not listed in the schema.

**Comment by jkoenig134** [comment]
@nenock [Connector Version `6.6.1`](https://github.com/nmshd/connector/pkgs/container/connector/303678376?tag=6.6.1) with the bugfix is available now.
