### ISSUE TITLE
[BUG] New discussions cannot be created

### ISSUE THREAD

**Issue by kulla** [nmshd/feedback#6]
**Describe the bug**
At https://github.com/nmshd/feedback/discussions I am not able to create a new discussion. The following screenshots shows how this site looks to me (button "New discussion" is missing):

![2022-01-03-184745_1300x854_scrot](https://user-images.githubusercontent.com/1327215/147962624-d4ee1e36-8b9e-4501-8c9f-7a980a0404e4.png)

**Comment by kulla** [comment]
The only place I have found where the access to discussions can be changed, is described at https://docs.github.com/en/organizations/managing-organization-settings/managing-discussion-creation-for-repositories-in-your-organization

Screenshot from the settings page of our organization:

![2022-01-03-185622_803x224_scrot](https://user-images.githubusercontent.com/1327215/147963388-6c86e4b5-54d3-45f9-b70f-74ede1fa1c0b.png)

**Comment by jkoenig134** [comment]
Should work now. Thanks!
