### ISSUE TITLE
[FEATURE] Specify `content` attribute of ConnectorRelationshipChangeRequest in the TypeScript SDK

### ISSUE THREAD

**Issue by kulla** [nmshd/feedback#8]
**Environment**
[TypeScript SDK](https://github.com/nmshd/cns-connector/tree/main/packages/sdk)

**Is your feature request related to a problem? Please describe.**
We use the [TypeScript SDK](https://github.com/nmshd/cns-connector/tree/main/packages/sdk) in our project (see [enmeshed-middleware.ts](https://github.com/serlo/api.serlo.org/blob/main/packages/server/src/internals/server/enmeshed-middleware.ts)). Since some attributes of the TypeScript SDK are `any` for example in [`ConnectorMessage`](https://github.com/nmshd/cns-connector/blob/main/packages/sdk/src/types/messages/ConnectorMessage.ts#L5) or in [`ConnectorRelationshipChangeRequest`](https://github.com/nmshd/cns-connector/blob/main/packages/sdk/src/types/relationships/ConnectorRelationshipChangeRequest.ts#L5) we ran into the following problems:

* Due to our eslint configurations we get an error each time we handle any types (like `Unsafe assignment of type any`). Therefore we would need to disable those eslint rules whenever we want to process the content of an `any` attribute.
* Using `any` is not type safe since it stops TypeScript from checking the code. So we cannot use the advantage of TypeScript to check our code for obvious errors (spelling errors, mismatched types, etc.).
* We also used the types in the TypeScript SDK as a documentation to see which payloads are send or received. Whoever whenever there was an `any` we would need to make example requests and log the results to see the actual JSON structure. This is tedious to do while developing.

**Describe the solution you'd like**
Specify each attribute in the TypeScript SDK which currently has the `any` attribute with new types. Avoid `any` and use other more safe types like `unknown` or `Record<string, ...>`.

**Describe alternatives you've considered**
We have copied the types into our repo (see [enmeshed-payload.ts](https://github.com/serlo/api.serlo.org/blob/main/packages/server/src/internals/server/enmeshed-payload.ts)) and replaced the `any` types manually where it was necessary. However that's not an elegant solution.

**Comment by jkoenig134** [comment]
The problem here is, that e.g. the content of a message or Relationship Template can have **any** content. This is user defined.

What about `Record<string, any>` is this also covered by the eslint rule?

**Comment by jkoenig134** [comment]
> We have copied the types into our repo (see enmeshed-payload.ts) and replaced the any types manually where it was necessary. 
>
> However that's not an elegant solution.

Please be careful, your replacements are not correct. These values are **any** / **unknown** per definition. You will have to typecheck these values instead of only assume it will have exactly these values.

**Comment by kulla** [comment]
> The problem here is, that e.g. the content of a message or Relationship Template can have any content. This is user defined.

Okay, I guess now I have a better understanding of enmeshed! I always asked myself what the purpose of `"content": { "prop1": "value", "prop2": 1 }` is in the swagger documentation of `POST /api/v1/RelationshipTemplate/Own`. Now I see the same object as the `content` of the response in the `RelationshipChange` I received via the webhook.

Am I right that each participant of enmeshed can freely decide what the properties of `content` are? So in my case the enmeshed app decides which content I get after accepting the relationship request?

> What about `Record<string, any>` is this also covered by the eslint rule?

Not really. We will end up in the same error only one level deeper in parsing the JSON. This also wouldn't show spelling errors (like accidentally writing `content.metdata` instead of `content.metadata`). When type checking should be enforced at the consumer side `unknown` would be a better choice than `any`.

The content of the `RelationshipRequest` I receive seems to have a clear structure based on the template I create. When the template has a `metadata: { sessionId: foo }` I get the same property in the webhook. When there is a `privacy` field in the template there is also one in the `content`. For those fields an attempt is:

```ts
// Metadata might be defined higher up in the type hierachy
interface RelationshipChange<Metadata={ [key in string]?: unknown }> {
  request: {
    content?: RelationshipRequest<Metadata> | ...
  }
  ...
}

interface RelationshipRequest<Metadata> {
  type: "RelationshipRequest"
  privacy?: string
  metadata: Metadata
  ...
}
```

Thus when I only have `{ sessionId: string }` in my application I can use this discrete type. Otherwise I have the default `{ [key in string]?: unknown }`.

However I haven't found the rules how the content of a `RelationshipRequest` content is created based on the template.

**Comment by kulla** [comment]
> Please be careful, your replacements are not correct. These values are **any** / **unknown** per definition. You will have to typecheck these values instead of only assume it will have exactly these values.

I know. We already have suspected that it will work only in our limited prototypes. For the future we plan to check the payload with tools like [io-ts](https://www.npmjs.com/package/io-ts).

**Comment by kulla** [comment]
> The problem here is, that e.g. the content of a message or Relationship Template can have **any** content. This is user defined.

True that! For messages and relationship templates this makes sense. Here `unknown` or (`Record<string, unknown>` in case of an arbitrary object) is IMHO better since it enforces type checking at the consumer site.

I mostly aim at [`ConnectorRelationshipChangeRequest.content`](https://github.com/nmshd/cns-connector/blob/f42dc7d1132df2533928b4e4fbe886fe65c44fb0/packages/sdk/src/types/relationships/ConnectorRelationshipChangeRequest.ts#L5) since many of our eslint errors are connected to this type. Thus I have changed the title...

Besides when sending a message / creating a relationship template more concrete types can help a developer. For example [SendMessageRequest.ts](https://github.com/nmshd/cns-connector/blob/main/packages/sdk/src/types/messages/requests/SendMessageRequest.ts) can be extended to

```ts
interface SendMessageRequest {
    recipients: string[];
    content: Mail | RequestMail | unknown;
    attachments?: string[];
}

interface Mail {
  '@type': 'Mail',
  to: string[],
  subject: string,
  body: string
}

interface RequestMail extends Omit<Mail, "@type"> {
  '@type': "RequestMail"
  requests: ...
}
```

So the default messages for an enmeshed app are clearly documented. One can also use:

```ts
interface SendMessageRequest<MyContent = unknown> {
    recipients: string[];
    content: Mail | RequestMail | MyContent;
    attachments?: string[];
}
```

So with the generic type `MyContent` one can define the concrete type of messages one wants to send. With `SendMessageRequest<never>` only the predefined messages are possible.

**Comment by jkoenig134** [comment]
Thanks for the input, we will discuss that internal.

**Comment by stnmtz** [comment]
You are both right, so here are my 2 cents on this. A quick disclaimer upfront: I did not use the Connector SDK so far and thus might misinterpret some things.

- Enmeshed does not want do restrict the format of the used payload - at least on the transport layer. If two parties want's to communicate a structured lunch menu with each other via messages, they can do so.
- "... on the transport layer" is the interesting thing here, as the app runs on a layer above the transport layer, we call the consumption layer. Here, we are required to define at least a basic structure, like:
  - Attributes for daily business (Person, Addresses, Communications)
  - Messages end-users will understand (Mail, RequestMail)
  - Requests, Shared/Received Attributes of Contacts, have Contact names, and so on...
- The connector so far runs on the transport layer. We can only validate messages on the connector/backbone (e.g. is there a 
 relationship to this and that address), but not the payload of messages - it is not the connector's business to do so.
- Same goes for the connector SDK - it so far is transport layer only.
- The dilemma comes from the point, that a connector (transport layer, payload agnostic) is usually used to talk with an app (consumption layer, payload specific).

So how do we solve that?
1. We require types for the payload the app understands. No matter who is using these types. For this we have the https://github.com/nmshd/cns-content repository, but it lacks documentation and also Templates and Requests are so far not typed at all (I think of them as untyped version 0 payload)
2. Either the connector needs to understand these types with "consumption routes", e.g. POST /Mails instead of POST /Messages, or some other component must do this on top of the connector. Both based on the types we defined in 1).
3. The identities should know, which kind of types are supported. So far, you cannot explicitly know if the identity you talk with is an app (supporting the consumption layer) or an connector (supporting the transport layer) or something which even understands a lunch menu.
4. Best case: it could be validated if a payload is supported by the recipient before one sends a message.

We're working on these things, but would be very happy for any contribution/feedback :)

**Comment by stnmtz** [comment]
Here a first glimpse on typed template bodies so far. There are still some errors in the RelationshipRequest. Again, I don't made up my mind yet if this should be within the ConnectorSDK. 

```typescript
export interface IRelationshipTemplateBodyV0 {
    ifRelationshipExists?: IRelationshipTemplateBodyRelationshipExistsActionV0
    attributes?: IRelationshipTemplateBodyAttributeV0[]
    request?: IRelationshipTemplateBodyRequestV0
    privacy?: IRelationshipTemplateBodyPrivacyV0 | IRelationshipTemplateBodyPrivacyV0[]
    metadata?: any
    session?: any
    theme?: string
}

export interface IRelationshipTemplateBodyPrivacyV0 {
    link: string
    uri: string
    label: string
    activeConsent?: boolean
    text: string
    required?: boolean
    default?: boolean
}

export interface IRelationshipTemplateBodyRequestV0 {
    required?: IRelationshipTemplateBodyRequestAttributeV0[]
    optional?: IRelationshipTemplateBodyRequestAttributeV0[]
    create?: IRelationshipTemplateBodyRequestAttributeCreateV0[]
    authorizations?: IRelationshipTemplateBodyRequestAuthorizationV0[]
    questions?: IRelationshipTemplateBodyRequestQuestionV0[]
}

export interface IRelationshipTemplateBodyRequestAuthorizationV0 {
    id: string
    title: string
    duration?: string
    required?: boolean
}

export interface IRelationshipTemplateBodyRequestQuestionV0 {
    key: string
    label?: string
    type: RelationshipTemplateBodyRequestQuestionTypeV0
    selectedKey?: string
    readonly?: boolean
    value?: string
    values?: IRelationshipTemplateBodyRequestQuestionValueV0[]
    help?: string
}

export interface IRelationshipTemplateBodyRequestQuestionValueV0 {
    key: string
    label: string
}

export enum RelationshipTemplateBodyRequestQuestionTypeV0 {
    Invisible = "invisible",
    Dropdown = "dropdown",
    Date = "date",
    String = "string",
    Text = "text"
}

export interface IRelationshipTemplateBodyRequestAttributeV0 {
    attribute: string
}

export interface IRelationshipTemplateBodyRequestAttributeCreateV0 {
    attribute: string
    value: any
}

export interface IRelationshipTemplateBodyAttributeV0 {
    name: string
    value: string
}

export interface IRelationshipTemplateBodyRelationshipExistsActionV0 {
    action: RelationshipTemplateBodyRelationshipExistsActionTypeV0
    content: any
}

export enum RelationshipTemplateBodyRelationshipExistsActionTypeV0 {
    Message = "message"
}
```

**Comment by kulla** [comment]
> Enmeshed does not want do restrict the format of the used payload - at least on the transport layer. If two parties want's to communicate a structured lunch menu with each other via messages, they can do so.

Thanks for the clarification. This wasn't clear to me in the beginning. Having types for the consumer layer as well would be great and it clarifies which messages shall be send / how the template need to be set up. For the integration of the consumer types into the connector SDK I would differentiate between sending and consuming:

* For send message a client should be able to define which kind of messages should be send so that TypeScript can be used to check whether we only send those messages (for example with generic types as in my comment above). Maybe the payload types the app understands should be the default one. 
* For receiving one can either configure the connector to type check the messages or one can pass a type checker (for example with [io-ts](https://www.npmjs.com/package/io-ts)) for parsing the messages. Setting the type to `unknown` is also fine since in reality one can receive any payloads here when I understand you well...

> Best case: it could be validated if a payload is supported by the recipient before one sends a message.

I would do the type checking at the receiving end. It would be great if the SDK supports this already. Lets take the example of an service using enmeshed only to share lunch menus. The configuration might be:

```ts
import * as t from 'io-ts'

const client = ConnectorClient.create({
   baseUrl: "...",
   apiKey: "...",
   supportedMessages: t.array({
     t.type({
       name: t.string,
       price: t.number,
       ingredients: t.string[]
     })
  })
});
```

The decoder can be used that only lunch menus of the form `{ name: string, price: number, ingredients: string[] }` can be received and other messages are dropped / result in a "parse error". The connector SDK might ship decoders for messages the app understands as well.

**Comment by stnmtz** [comment]
> Having types for the consumer layer as well would be great and it clarifies which messages shall be send / how the template need to be set up. For the integration of the consumer types into the connector SDK I would differentiate between sending and consuming:

> I would do the type checking at the receiving end. It would be great if the SDK supports this already. Lets take the example of an service using enmeshed only to share lunch menus.

For communication between connectors, I would bluntly say it is up to the one(s) who define a "lunch menu" to figure out, how to identify/parse/process a lunch menu message from the rest of the messages.

For the app, it is a complete different story. The app doesn't know about lunch menus so far. Although you could ship decoders to lunch menus, the app wouldn't know how to render them to the user or to let them know, where and how the user could install "Custom Type lunch menu".

Thus, a decoder would not suffice for the app, a whole "UI-Module for Lunch Menus" would be required. This brings us to the point, where we require some kind of a "UI-Module Repository for Custom Types", where developers could register a "Custom Type Lunch Menu". And a kind of sanity and security checks for each and every module, as we are dealing with highly sensitive data here and any UI module might have (accidently or not) access to the whole scope of the identity. You could think of sand-boxed UI Modules within iframes then, as we are based on web-technology. However, all of this is unfortunately out of scope for now.

So far, my thoughts are to strictly restrict the consumption layer to process an absolute minimalistic "enmeshed communication protocol" which will suffice for 80% of the actual processes. Data sharing, data querying, data entry, professional communication kind of way. First, we solve identity- and domain-specific attributes, then we will tackle identity- or domain-specific communication on the consumption layer :)

**Comment by jkoenig134** [comment]
Hi @kulla.
I close this issue because we are now using `unknown` instead of `any` for all external types. `any` is only used internally, if these occurrences are also problematic for you feel free to re-open the issue and we'll investigate how to resolve them.

**Comment by kulla** [comment]
> Hi @kulla.
> I close this issue because we are now using `unknown` instead of `any` for all external types. `any` is only used internally, if these occurrences are also problematic for you feel free to re-open the issue and we'll investigate how to resolve them.

No worries, `unknown` is fine in this case since it enforces a parsing when receiving data. For sending data one can consider that there is a possibility to narrow down the type via a type parameter.
